export let affiliations = [
    "Coalition of the Formerly Living",
    "Wicker Men",
    "Circle of Cernunnos",
    "Church of Crom",
    "Church of Mitra",
    "Temple of Brighid",
    "Cult of Set",
    "Cult of Nergal",
    "Merry Men",
    "Cult of the Black Amphora",
    "Order of the Sphinx",
    "Order of the Rose",
    "Order of the Basilisk",
    "Order of the Candle",
    "Order of the Lantern",
    "Order of the Hearth",
    "Skylords",
    "Blackhands",
    "Thieves' Guild",
    "Bloody Cabal",
    "Shadow Cult",
    "Guild of Sorcerers",
    "Society of Scrutinous Scholars",
    "Royal Gardeners' Society",
    "The Sulfur Company",
    "Merchants' Guild",
    "Royal Arcane Institute",
    "Institute of the Arcane",
    "Aldred's Two Hundred",
    "Highpeak Clan",
    "Barrett's Privateers",
    "Northwest Passage Explorers",
    "Finch's Giants",
    "Bramble Bastards",
    "Witches of the Westmorland",
    "The Night Guard",
    "Scarborough Sorcerers",
    "Herbal Guild",
    "Barrow Delvers' Society",
    "The Lock Keepers",
    "Marduk's Last Watch",
    "Woodbridge Dogs",
    "House of the Holy",
    "Blackdogs",
    "Sword of St. Tristan",
    "House of Red",
    "Harbingers of the Dark Star",
    "Children of the Moon Mountains",
    "Dire Wolves",
    "Shield-Maidens of Veborg",
    "Canso Witch-Hunters",
    "Sun Warriors",
    "Valkyries of Sigyn",
    "The Wild Boars",
    "Nightblades",
    "Masters of the Universe",
    "Wheel of Fire",
    "Royal Metallurgists",
    "The Alloy Supreme",
    "Zenith's Hammer",
    "The Transcendants",
];

export let attunementsItems = [
    // Magical instruments
    "Crystal ball",
    "Magic wand",
    "Magic rod",
    "Wizard's staff",
    // Religious items
    "Holy symbol",
    "Reliquary",
    // Texts
    "Magic scroll",
    "Spellbook",
    "Necronomicon",
    // Weapons
    "Axe",
    "Sword",
    "Club",
    "Crossbow",
    "Dagger",
    "Dart",
    "Flail",
    "Greatsword",
    "Battle axe",
    "Halberd",
    "Pole arm",
    "Javelin",
    "Longbow",
    "Mace",
    "Warhammer",
    "Morning star",
    "Musket",
    "Pistol",
    "Quarterstaff",
    "Scimitar",
    "Shortbow",
    "Shortsword",
    "Sling",
    "Spear",
    "Throwing knife",
    "Throwing axe",
    // "Exotic" weapons
    "Throwing star",
    "Spiked chain",
    "Kukri",
    "Nunchaku",
    "Two-bladed sword",
    "Bolas",
    "Net",
    "Parrying dagger",
    "Rapier",
    "Blowpipe",
    "Shield",
    // Mundane items
    "Walking stick",
    // Adventuring items
    "Sledgehammer",
    "Ten-foot pole",
    "Rope",
    "Elven cloak",
    "Dueling cloak",
    "Alchemy kit",
    "Grappling hook",
    "Playing cards",
    "Dice set"
];

export let attunementsOther = [
    // Animals
    "Dog",
    "Hound",
    "Jackal",
    "Wolf",
    "Fox",
    "Horse",
    "Mule",
    "Donkey",
    "Monkey",
    "Cat",
    "Bobcat",
    "Lynx",
    "Raccoon",
    "Cougar",
    "Elk",
    "Bear",
    "Badger",
    "Mole",
    "Weasel",
    "Ferret",
    "Mongoose",
    "Rat",
    "Mouse",
    "Bat",
    "Raven",
    "Parrot",
    "Hawk",
    "Falcon",
    "Eagle",
    "Owl",
    "Magpie",
    // People
    "Archery master",
    "Sword master",
    "Master monk",
    "Ringleader",
    "Bandit king",
    "Master ninja",
    "Scholar of history",
    "Scholar of botany",
    "Scholar of naturalism",
    "Scholar of magic",
];

export let abilities = [
    "1. Protect ally from harm",
    "2. Push enemy after successful attack",
    "3. Cling to large foe",
    "4. Work up battle frenzy",
    "5. Give tactical instruction to ally",
    "6. Encourage allies or strike fear in enemies",
    "7. Double attack with melee and ranged weapons",
    "8. Parry",
];

export let miracles = [
    "Pyroclastic Flow",
    "Animate Dead",
    "Open Mind",
    "Bend Mind",
    "Crumble",
    "Magnetism",
    "Magnetic Resonance",
    "Bless",
    "Curse",
    "Hex",
    "Lightning Conduit",
    "Thunderstep",
    "Hellfrost",
    "Demonfire",
    "Light",
    "Darkness",
    "Healing Water",
    "Cleansing Fire",
    "Haste",
    "Sophronia's East Wind",
    "Berenger's Blessing",
    "Mirror Walking",
    "Shadowstep",
    "Psychosomatism",
    "Illusory Demons",
    "Hallow",
    "Corrupt",
    "Sanctify",
    "Envenom",
    "Speak with Animals",
    "Sacred Geometry",
    "Magic Number",
    "Air Bubble",
    "Acid Arrow",
    "Sanguinomancy",
    "Charm",
    "Detect Water",
    "Spider Shape",
    "Speak with Ants",
    "Speak with Plants",
    "Animate Plants",
    "Animate Rope",
    "Apathy",
    "Clarion Call",
    "Defenestrate",
    "Animate Construct",
    "Truesight",
    "Nightvision",
    "Visions of Night",
    "Battle Trance",
    "Bilocation",
    "Mirror Image",
    "Time Warp",
    "Gust",
    "Control Wind",
    "Blink",
    "Blur",
    "Bookwalking",
    "Libromancy",
    "Burning Hands",
    "Conflagrate",
    "Calm Emotions",
    "Cause Fear",
    "Summon Chains",
    "Static Charge",
    "Imbue Charge",
    "Electrify",
    "Halcyon Days",
    "Cleanse",
    "Identify",
    "Chill Metal",
    "Heat Metal",
    "Warp Metal",
    "Entropy",
    "Reverse Thermodynamics",
    "Bend Time",
    "Commune with Nature",
    "Summon Bird",
    "False Life",
    "Cone of Cold",
    "Conjure Food",
    "Pestilence",
    "Contagion",
    "Speak with Wind",
    "Cosmic Ray",
    "Neutrino Burst",
    "Conjure Weapon",
    "Conjure Armor",
    "Golden Glory",
    "Despair",
    "Reincarnate",
    "Daze",
    "Ward Death",
    "Ward Magic",
    "Suppress Pain",
    "Decapitate",
    "Detect",
    "Detect Secrets",
    "Read Thoughts",
    "Clairvoyance",
    "Devolve",
    "Invoke Divinity",
    "Dream",
    "Dreamwalk",
    "Alter Lore",
    "Echo",
    "Earthquake",
    "Ectoplasm",
    "Enervate",
    "Entangle",
    "Enthrall",
    "Mind Slave",
    "Explosive Runes",
    "Faerie Fire",
    "Faerie Flight",
    "Acorn of Far Travel",
    "Feather Fall",
    "Finger of Death",
    "Fireball",
    "Petrify",
    "Warp Flesh",
    "Winged Feet",
    "Forbiddance",
    "Divination",
    "Foresight",
    "Slumber",
    "Feeblemind",
    "Ghost Form",
    "Lycanthropy",
    "Word of Power",
    "Wind Walk",
    "Web",
    "Banshee Wail",
    "Control Vermin",
    "Part the Veil",
    "Vampirism",
    "Create Revenant",
    "Divine Prophecy",
    "Undeath",
    "Unholy Grasp",
    "Hand of Mercy",
    "Magical Tattoo",
    "Telepathy",
    "Mindwipe",
    "Stop Time",
    "Toxic Blood",
    "Truespeak",
    "Sympathy",
    "Synesthesia",
    "Anesthetize",
    "Summon Demon",
    "Summon Angel",
    "Suppress Magic",
    "Sunburst",
    "Crown of God",
    "Control Weather",
    "Summon Storm",
    "Silence",
    "Amplify Noise",
    "Engender Hatred",
    "Sever Soul",
    "Astral Projection",
    "Slow",
    "Protection from Evil",
    "Shield of Faith",
    "Mind's Eye",
    "Share Senses",
    "Possess",
    "Fury of the Sea",
    "Deep One's Blessing",
    "Sacred Seal",
    "Rage",
    "Ray of Frost",
    "Shrink",
    "Regenerate",
    "Cure Disease",
    "Pyrotechnics",
    "Protection from Spells",
    "Panacea",
    "Polymorph",
    "Plane Shift",
    "Phantom Foe",
    "Binding Oath",
    "Aura of Wisdom",
    "Aura of Courage",
    "Aura of Protection",
    "Aura of Fear",
    "Mirage",
    "Illusion",
    "Lunar Blessing",
    "Solar Blessing",
    "Mutagenic Blood",
    "Magic Jar",
    "Locate Person",
    "Locate Object",
    "Litany against Fear",
    "Lock",
    "Invisibility",
    "Shape Stone",
    "X-Ray Vision",
    "Infravision",
    "Judgement of Light",
    "Judgement of Darkness",
    "Holy Judgement",
    "Unholy Judgement",
    "Irresistible Dance",
    "Hideous Laughter",
    "Zone of Truth",
    "Icy Veins",
    "Coldsnap",
    "Illusory Wall",
    "Hide Between Worlds",
    "Terrible Visage",
    "Grease",
    "Commune with Stars",
    "Tentacle Arm",
    "Gills",
    "Retractable Claws",
    "Grow Organ",
    "Bifurcate",
];

export let armors = [
    {
        name: "Cloth armor",
        armorClass: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Leather armor",
        armorClass: 2,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Studded leather armor",
        armorClass: 3,
        allowedClasses: ["Deft", "Strong"],
    },
    {
        name: "Chainmail",
        armorClass: 4,
        allowedClasses: ["Strong"],
    },
    {
        name: "Splint mail",
        armorClass: 5,
        allowedClasses: ["Strong"],
    },
    {
        name: "Full plate",
        armorClass: 6,
        allowedClasses: ["Strong"],
    },
];

export let weapons = [
    {
        name: "Axe",
        namePlural: "Axes",
        damage: "1d6+1",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Sword",
        namePlural: "Swords",
        damage: "1d6+1",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Club",
        namePlural: "Clubs",
        damage: "1d6-2",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Dagger",
        namePlural: "Daggers",
        damage: "1d6-2",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Flail",
        namePlural: "Flails",
        damage: "1d6",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Greatsword",
        namePlural: "Greatswords",
        damage: "1d6+2",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong"],
    },
    {
        name: "Battle axe",
        namePlural: "Battle axes",
        damage: "1d6+2",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong"],
    },
    {
        name: "Halberd",
        namePlural: "Halberds",
        damage: "1d6+1",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong"],
    },
    {
        name: "Polearm",
        namePlural: "Polearms",
        damage: "1d6+1",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong"],
    },
    {
        name: "Mace",
        namePlural: "Maces",
        damage: "1d6",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Warhammer",
        namePlural: "Warhammers",
        damage: "1d6",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Morningstar",
        namePlural: "Morningstars",
        damage: "1d6",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Quarterstaff",
        namePlural: "Quarterstaves",
        damage: "1d6-1",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Scimitar",
        namePlural: "Scimitars",
        damage: "1d6",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Shortsword",
        namePlural: "Shortswords",
        damage: "1d6",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Spear",
        namePlural: "Spears",
        damage: "1d6",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    }, {
        name: "Crossbow",
        namePlural: "Crossbows",
        damage: "1d6+1",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Dart",
        namePlural: "Darts",
        damage: "1",
        quantityDefault: 12,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Javelin",
        namePlural: "Javelins",
        damage: "1d6",
        quantityDefault: 3,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Longbow",
        namePlural: "Longbows",
        damage: "1d6",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong"],
    },
    {
        name: "Musket",
        namePlural: "Muskets",
        damage: "1d6+2",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Pistol",
        namePlural: "Pistols",
        damage: "1d6+1",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Shortbow",
        namePlural: "Shortbows",
        damage: "1d6-1",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong"],
    },
    {
        name: "Sling",
        namePlural: "Slings",
        damage: "1d6-2",
        quantityDefault: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Throwing knife",
        namePlural: "Throwing knives",
        damage: "1d6-2",
        quantityDefault: 6,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Throwing axe",
        namePlural: "Throwing axes",
        damage: "1d6-2",
        quantityDefault: 3,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
];

export let items = [
    { name: "Backpack", namePlural: "Backpacks", costUnit: 5, defaultQuantity: 1, },
    { name: "Bandage", namePlural: "Bandages", costUnit: 0.4, defaultQuantity: 5, },
    { name: "Compass", namePlural: "Compasses", costUnit: 50, defaultQuantity: 1, },
    { name: "Crowbar", namePlural: "Crowbars", costUnit: 5, defaultQuantity: 1, },
    { name: "Flint & steel", namePlural: "Flints & steels", costUnit: 5, defaultQuantity: 1, },
    { name: "Grappling hook", namePlural: "Grappling hooks", costUnit: 5, defaultQuantity: 1, },
    { name: "Hammer", namePlural: "Hammers", costUnit: 3, defaultQuantity: 1, },
    { name: "Holy symbol", namePlural: "Holy symbols", costUnit: 2, defaultQuantity: 1, },
    { name: "Lantern", namePlural: "Lanterns", costUnit: 10, defaultQuantity: 1, },
    { name: "Lockpick", namePlural: "Lockpicks", costUnit: 20, defaultQuantity: 1, },
    { name: "Map", namePlural: "Maps", costUnit: 20, defaultQuantity: 1, },
    { name: "Mirror", namePlural: "Mirrors", costUnit: 5, defaultQuantity: 1, },
    { name: "Oil flask", namePlural: "Oil flasks", costUnit: 2, defaultQuantity: 1, },
    { name: "Pole", namePlural: "Poles", costUnit: 1, defaultQuantity: 1, },
    { name: "Ration", namePlural: "Rations", costUnit: 3, defaultQuantity: 1, },
    { name: "Rope", namePlural: "Ropes", costUnit: 1, defaultQuantity: 1, },
    { name: "Sack", namePlural: "Sacks", costUnit: 1, defaultQuantity: 1, },
    { name: "Shovel", namePlural: "Shovels", costUnit: 5, defaultQuantity: 1, },
    { name: "Stake", namePlural: "Stakes", costUnit: 0.2, defaultQuantity: 6, },
    { name: "Spike", namePlural: "Spikes", costUnit: 1, defaultQuantity: 6, },
    { name: "Tinderbox", namePlural: "Tinderboxes", costUnit: 10, defaultQuantity: 1, },
    { name: "Torch", namePlural: "Torches", costUnit: 0.2, defaultQuantity: 6, },
    { name: "Waterskin", namePlural: "Waterskins", costUnit: 3, defaultQuantity: 1, },
];

export let namesPrefixes = [
    "Clubfoot",
    "Crazy",
    "Do-Nothing",
    "One-Eyed",
    "Blind",
    "Brave",
    "Accursed",
    "Bald",
    "Cruel",
    "Gentle",
    "Good",
    "Grim",
    "Holy",
    "Hairy",
    "Lame",
    "Mad",
    "Old",
    "Pale",
    "Quiet",
    "Small",
    "Strong",
    "Swift",
    "Tall",
    "Terrible",
    "Wicked",
    "Wise",
];

export let namesPrimary = [
    "Blaine",
    "Matthew",
    "Morgan",
    "Francisco",
    "James",
    "Richard",
    "Dinadan",
    "Alan",
    "Aldred",
    "Eluard",
    "Arnold",
    "Henry",
    "Basil",
    "Jocelyn",
    "Cyr",
    "Balin",
    "George",
    "Eliot",
    "Frederick",
    "Alexander",
    "Percival",
    "Anselm",
    "Albert",
    "Urian",
    "Tristram",
    "Berenger",
    "Martin",
    "Merek",
    "Herman",
    "Hildebrand",
    "Edwin",
    "Gilbert",
    "Bliant",
    "Bennet",
    "Bryce",
    "Castor",
    "Giles",
    "Gunter",
    "Bernard",
    "Arthur",
    "Nigel",
    "Lucan",
    "Lionel",
    "Bartholomew",
    "Bardolph",
    "Barnabas",
    "Bertram",
    "Wolfstan",
    "Hardwin",
    "Hamond",
    "Faramond",
    "Herbert",
    "Alisander",
    "Ulric",
    "Galleron",
    "Solomon",
    "Sampson",
    "Tobias",
    "Charles",
    "Diggory",
    "Drogo",
    "Hugh",
    "Baudwin",
    "Everard",
    "Nicholas",
    "Leofwin",
    "Amis",
    "Ranulf",
    "Fulke",
    "Theobald",
    "Rowan",
    "Geoffrey",
    "Gervase",
    "Gerard",
    "Godwyn",
    "Philip",
    "Warin",
    "Warner",
    "Thomas",
    "Brom",
    "Hamon",
    "Thurstan",
    "Robert",
    "Roland",
    "Rolf",
    "Walter",
    "Laurence",
    "Reginald",
    "Aglovale",
    "Sayer",
    "Timm",
    "Piers",
    "Cedric",
    "Randel",
    "Denis",
    "Elias",
    "Gabriel",
    "Hector",
    "Humphrey",
    "Gamel",
    "Gregory",
    "Jasper",
    "Jeremy",
    "Isaac",
    "Ingram",
    "Isembard",
    "Manfred",
    "Ives",
    "William",
    "Lucius",
    "Wymond",
    "Lambert",
    "Blaise",
    "Griffith",
    "Mabon",
    "Hubert",
    "Gerald",
    "Eustace",
    "Emory",
    "Adam",
    "Adelard",
    "Alphonse",
    "Turstin",
    "Guy",
    "Peter",
    "Osric",
    "Ogier",
    "Gareth",
    "Maynard",
    "Miles",
    "Elaine",
    "Sarah",
    "Sela",
    "Sigga",
    "Susanna",
    "Althea",
    "Alma",
    "Artemisia",
    "Anne",
    "Anais",
    "Acelina",
    "Aelina",
    "Aldith",
    "Audry",
    "Augusta",
    "Brangwine",
    "Bridget",
    "Genevieve",
    "Guinevere",
    "Catelin",
    "Caterina",
    "Dionisia",
    "Mary",
    "Molly",
    "Margaret",
    "Margery",
    "Martha",
    "Elizabeth",
    "Elysande",
    "Cristina",
    "Giselle",
    "Regina",
    "Ricolda",
    "Roana",
    "Barbetta",
    "Bertha",
    "Clarice",
    "Amelina",
    "Cecily",
    "Edith",
    "Elle",
    "Juliana",
    "Ivette",
    "Adelina",
    "Agnes",
    "Alis",
    "Alyson",
    "Dameta",
    "Paulina",
    "Petronilla",
    "Edeva",
    "Eglenti",
    "Evelune",
    "Emeline",
    "Emma",
    "Joan",
    "Johanna",
    "Lavina",
    "Lena",
    "Lovota",
    "Lillian",
    "Maud",
    "Milicent",
    "Magdalen",
    "Isabella",
    "Caesaria",
    "Douglas",
    "Delia",
    "Sapphira",
    "Sophronia",
    "Tephania",
    "Theda",
    "Thora",
    "Odelina",
    "Oliva",
    "Orella",
    "Venetia",
    "Ysmeine",
    "Gracia",
    "Gratia",
    "Swanhild",
    "Sybil",
    "Mathilde",
    "Ida",
    "Ingerith",
    "Isemay",
    "Celestria",
    "Constance",
    "Eleanor",
    "Amicia",
    "Avina",
    "Athelina",
    "Eva",
    "Gundred",
    "Felicia",
    "Floria",
    "Isolda",
    "Linota",
    "Cassandra",
    "Lucia",
    "Helewisa",
    "Justina",
    "Joyce",
    "Joya",
    "Nesta",
    "Sabina",
    "Gisela",
    "Rosa",
    "Rosamund",
    "Evaine",
    "Viviane",
    "Laudine",
    "Letia",
    "Leticia",
    "Legarda",
    "Lia",
    "Lunete",
    "Florence",
    "Gwendolen",
    "Nicola",
    "Blanche",
    "Beatrice",
    "Marie",
    "Marion",
    "Mirielda",
];

export let namesSuffixes = [
    "the Hard",
    "the Soft",
    "of the North",
    "of the East",
    "of the South",
    "of the West",
    "the Black",
    "the White",
    "the Red",
    "the Yellow",
    "of the Wood",
    "of the Mountain",
    "of the Valley",
    "of the River",
    "of the Lake",
    "the Elder",
    "the Younger",
    "the Brave",
    "the Great",
    "the Magnificent",
    "the Able",
    "the Accursed",
    "the Bald",
    "the Bear",
    "the Cruel",
    "the Damned",
    "the Exile",
    "the Gentle",
    "the Good",
    "the Grim",
    "the Hammer",
    "the Holy",
    "the Hairy",
    "the Impaler",
    "the Kind",
    "the Lame",
    "the Lion",
    "the Wolf",
    "the Mad",
    "the Old",
    "the Pale",
    "the Quiet",
    "the Rose",
    "the Seer",
    "the Small",
    "the Spider",
    "the Strong",
    "the Swift",
    "the Tall",
    "the Terrible",
    "the Wicked",
    "the Wise",
    "of the Sun",
    "of the Moon",
    "Fairhair",
    "Bloodaxe",
    "Crookback",
    "Flatnose",
    "Forkbeard",
    "Greyfell",
    "Greymantle",
    "Longshanks",
    "Ironside",
    "Moneybags",
    "Oathbreaker",
    "One-Eye",
    "Ploughpenny",
    "Roundhead",
    "Thunderbolt",
    "Oakeshott",
];

export let vocations = [
    // Warriors
    "Barbarian",
    "Bounty Hunter",
    "Crusader",
    "Gladiator",
    "Knight",
    "Outrider",
    "Pit Fighter",
    "Pugilist",
    "Templar",
    "Vigilante",
    "Warrior",

    // Warrior-Mages
    "Battlemage",
    "Paladin",
    "Spellsword",
    "Warpriest",

    // Mages
    "Cleric",
    "Conjurer",
    "Demonologist",
    "Diviner",
    "Druid",
    "Elementalist",
    "Exorcist",
    "Healer",
    "Illusionist",
    "Mage",
    "Medium",
    "Mystic",
    "Necromancer",
    "Oracle",
    "Priest",
    "Psion",
    "Psychic",
    "Shaman",
    "Soothsayer",
    "Sorcerer",
    "Summoner",
    "Thaumaturgist",
    "Warlock",
    "Warmage",
    "Wizard",

    // Mage-Rogues

    // Rogues
    "Acrobat",
    "Agent",
    "Archer",
    "Assassin",
    "Bard",
    "Duelist",
    "Fencer",
    "Hunter",
    "Marksman",
    "Monk",
    "Ninja",
    "Ranger",
    "Rogue",
    "Scout",
    "Spy",
    "Thief",

    // Scholars
    "Alchemist",
    "Apothecary",
    "Astronomer",
    "Astrologist",
    "Doctor",
    "Engineer",
    "Medic",
    "Numerologist",
    "Philosopher",
    "Surgeon",
    "Physicker",
    "Mathematician",
    "Naturalist",
    "Botanist",

    // Mundane
    "Aristocrat",
    "Merchant",
    "Orator",
    "Pilgrim",
    "Pirate",
    "Sailor",
    "Woodsman",

    // Other
    "Inquisitor",
];

export let appearances = [
    // Complexion
    "Pale as a ghost",
    "Covered in freckles",
    "Skin has a blue tint",
    "Jet-black skin",
    // Scars
    "Single long scar across one eye",
    "Web of scars from lightning strike",
    "Three long scars, from the claws of a beast",
    "Numerous battle scars",
    "Burn marks on hands",
    "Burn marks on half of face",
    "Covered in pox marks",
    // Congenital
    "Hunchback",
    "Clubfoot",
    "Has six fingers on each hand",
    "Cleft lip",
];

export let appearancesHair = [
    "Shock of white hair",
    "Flame-red hair",
    "White-blonde hair",
    "Night-black hair",
    "Tonsured hair, like a friar",
    "Shaved head",
    "Long, braided hair",
    "Close-cropped hair",
    "Long, curly hair",
];

export let appearancesBuild = [
    "Tall and muscular",
    "Tall and lanky",
    "Short but slim",
    "Short and stout",
    "Broad-shouldered and barrel-chested",
    "Skeletally thin",
    "Tall and fat",
];

export let quirks = [
    // Background
    "Used to be a farmer",
    "Used to be a cobbler",
    "Used to be a blacksmith",
    "Used to be a brewer",
    // Studies
    "Studied magic in their youth",
    "Very curious about magic",
    "Not a big fan of magic",
    // Family
    "Family eaten by trolls",
    "Family eaten by ghouls",
    "Family killed by inquisitors",
    "Family killed by crusaders",
    "Family killed by orcs",
    // Phobias
    "Deathly afraid of spiders",
    "Deathly afraid of undead",
    "Hates the dark",
    // Personality
    "Extremely forgetful",
    "Quick to anger",
    "Never forgets a slight",
    "Quick to forgive",
    "Very easygoing",
    "Makes friends with everyone",
    "Absent-minded--always thinking about something else",
    // Arts
    "Always singing sea shanties",
    "Composes poems",
    "Composes ballads",
    "Writes love stories",
    "Whistles incessantly",
    "Illiterate and self-conscious about it",
    // Drugs
    "Teeth stained from chewing tobacco",
    "Smokes pipe at every chance",
    "Too fond of drink",
    "Loves wine more than anything",
    "Despises drinking",
    // Food
    "Always stopping to forage for food",
    "Eats whenever they have the opportunity",
    "Passionate about mushrooms",
    "Doesn't eat meat",
    // Outdoorsmanship
    "Loves to hunt",
    "Excellent at lighting fires",
    "Likes fire a little too much",
    "Knows how to set a snare",
    // Habits
    "Always sharpening or polishing weapons",
    "Constantly looks over their shoulder",
    "Mutters under their breath",
    "Collects small shiny objects",
    "Knows a lot about coins",
];

export let genders = [
    {
        gender: "Male",
        pronounSubject: "he",
        pronounObject: "him",
        pronounPossessiveDependent: "his",
        pronounPossessiveIndependent: "his",
        pronounReflexive: "himself",
    },
    {
        gender: "Female",
        pronounSubject: "she",
        pronounObject: "her",
        pronounPossessiveDependent: "her",
        pronounPossessiveIndependent: "hers",
        pronounReflexive: "herself",
    },
    {
        gender: "Other",
        pronounSubject: "they",
        pronounObject: "them",
        pronounPossessiveDependent: "their",
        pronounPossessiveIndependent: "theirs",
        pronounReflexive: "themself",
    },
];