export let affiliations = [
    "Wicker Men",
    "Circle of Cernunnos",
    "Church of Crom",
    "Church of Mitra",
    "Temple of Brighid",
    "Cult of Set",
    "Cult of Nergal",
    "Merry Men",
    "Cult of the Black Amphora",
    "Order of the Sphinx",
    "Order of the Rose",
    "Order of the Basilisk",
    "Order of the Candle",
    "Order of the Lantern",
    "Order of the Hearth",
    "Skylords",
    "Blackhands",
    "Thieves' Guild",
    "Bloody Cabal",
    "Shadow Cult",
    "Guild of Sorcerers",
    "Society of Scrutinous Scholars",
    "Royal Gardeners' Society",
    "The Sulfur Company",
    "Merchants' Guild",
    "Royal Arcane Institute",
    "Institute of the Arcane",
    "Aldred's Two Hundred",
    "Highpeak Clan",
    "Barrett's Privateers",
    "Northwest Passage Explorers",
    "Finch's Giants",
    "Bramble Bastards",
    "Witches of the Westmorland",
    "The Night Guard",
    "Scarborough Sorcerers",
    "Herbal Guild",
    "Barrow Delvers' Society",
    "The Lock Keepers",
    "Marduk's Last Watch",
    "Woodbridge Dogs",
    "House of the Holy",
    "Blackdogs",
    "Sword of St. Tristan",
    "House of Red",
    "Harbingers of the Dark Star",
    "Children of the Moon Mountains",
    "Dire Wolves",
    "Shield-Maidens of Veborg",
    "Canso Witch-Hunters",
    "Sun Warriors",
    "Valkyries of Sigyn",
    "The Wild Boars",
    "Nightblades",
    "Masters of the Universe",
    "Wheel of Fire",
    "Royal Metallurgists",
    "The Alloy Supreme",
    "Zenith's Hammer",
    "The Transcendants",
];

export let attunements = [
    "Random attunement 1",
    "Random attunement 2",
    "Random attunement 3",
    "Random attunement 4",
    "Random attunement 5",
    "Random attunement 6",
];

export let abilities = [
    "1. Protect ally from harm",
    "2. Push enemy after successful attack",
    "3. Cling to large foe",
    "4. Work up battle frenzy",
    "5. Give tactical instruction to ally",
    "6. Encourage allies or strike fear in enemies",
    "7. Double attack with melee and ranged weapons",
    "8. Parry",
];

export let miracles = [
    "Pyroclastic Flow",
    "Animate Dead",
    "Open Mind",
    "Bend Mind",
    "Crumble",
    "Magnetism",
    "Magnetic Resonance",
    "Bless",
    "Curse",
    "Hex",
    "Lightning Conduit",
    "Thunderstep",
    "Hellfrost",
    "Demonfire",
    "Light",
    "Darkness",
    "Healing Water",
    "Cleansing Fire",
    "Haste",
    "Sophronia's East Wind",
    "Berenger's Blessing",
    "Mirror Walking",
    "Shadowstep",
    "Psychosomatism",
    "Illusory Demons",
    "Hallow",
    "Corrupt",
    "Sanctify",
    "Envenom",
    "Speak with Animals",
];

export let armors = [
    {
        name: "Cloth armor",
        armorClass: 1,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Leather armor",
        armorClass: 2,
        allowedClasses: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Studded leather armor",
        armorClass: 3,
        allowedClasses: ["Deft", "Strong"],
    },
    {
        name: "Chainmail",
        armorClass: 4,
        allowedClasses: ["Strong"],
    },
    {
        name: "Splint mail",
        armorClass: 5,
        allowedClasses: ["Strong"],
    },
    {
        name: "Full plate",
        armorClass: 6,
        allowedClasses: ["Strong"],
    },
];

export let weapons = [
    {
        name: "Axe",
        namePlural: "Axes",
        damage: "1d6+1",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Sword",
        namePlural: "Swords",
        damage: "1d6+1",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Club",
        namePlural: "Clubs",
        damage: "1d6-2",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Dagger",
        namePlural: "Daggers",
        damage: "1d6-2",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Flail",
        namePlural: "Flails",
        damage: "1d6",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Greatsword",
        namePlural: "Greatswords",
        damage: "1d6+2",
        quantityDefault: 1,
        classes: ["Deft", "Strong"],
    },
    {
        name: "Battle axe",
        namePlural: "Battle axes",
        damage: "1d6+2",
        quantityDefault: 1,
        classes: ["Deft", "Strong"],
    },
    {
        name: "Halberd",
        namePlural: "Halberds",
        damage: "1d6+1",
        quantityDefault: 1,
        classes: ["Deft", "Strong"],
    },
    {
        name: "Polearm",
        namePlural: "Polearms",
        damage: "1d6+1",
        quantityDefault: 1,
        classes: ["Deft", "Strong"],
    },
    {
        name: "Mace",
        namePlural: "Maces",
        damage: "1d6",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Warhammer",
        namePlural: "Warhammers",
        damage: "1d6",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Morningstar",
        namePlural: "Morningstars",
        damage: "1d6",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Quarterstaff",
        namePlural: "Quarterstaves",
        damage: "1d6-1",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Scimitar",
        namePlural: "Scimitars",
        damage: "1d6",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Shortsword",
        namePlural: "Shortswords",
        damage: "1d6",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Spear",
        namePlural: "Spears",
        damage: "1d6",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    }, {
        name: "Crossbow",
        namePlural: "Crossbows",
        damage: "1d6+1",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Dart",
        namePlural: "Darts",
        damage: "1",
        quantityDefault: 12,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Javelin",
        namePlural: "Javelins",
        damage: "1d6",
        quantityDefault: 3,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Longbow",
        namePlural: "Longbows",
        damage: "1d6",
        quantityDefault: 1,
        classes: ["Deft", "Strong"],
    },
    {
        name: "Musket",
        namePlural: "Muskets",
        damage: "1d6+2",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Pistol",
        namePlural: "Pistols",
        damage: "1d6+1",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Shortbow",
        namePlural: "Shortbows",
        damage: "1d6-1",
        quantityDefault: 1,
        classes: ["Deft", "Strong"],
    },
    {
        name: "Sling",
        namePlural: "Slings",
        damage: "1d6-2",
        quantityDefault: 1,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Throwing knife",
        namePlural: "Throwing knives",
        damage: "1d6-2",
        quantityDefault: 6,
        classes: ["Deft", "Strong", "Wise"],
    },
    {
        name: "Throwing axe",
        namePlural: "Throwing axes",
        damage: "1d6-2",
        quantityDefault: 3,
        classes: ["Deft", "Strong", "Wise"],
    },
];

export let items = [
    { name: "Backpack", namePlural: "Backpacks", costUnit: 5, defaultQuantity: 1, },
    { name: "Bandage", namePlural: "Bandages", costUnit: 0.4, defaultQuantity: 5, },
    { name: "Compass", namePlural: "Compasses", costUnit: 50, defaultQuantity: 1, },
    { name: "Crowbar", namePlural: "Crowbars", costUnit: 5, defaultQuantity: 1, },
    { name: "Flint & steel", namePlural: "Flints & steels", costUnit: 5, defaultQuantity: 1, },
    { name: "Grappling hook", namePlural: "Grappling hooks", costUnit: 5, defaultQuantity: 1, },
    { name: "Hammer", namePlural: "Hammers", costUnit: 3, defaultQuantity: 1, },
    { name: "Holy symbol", namePlural: "Holy symbols", costUnit: 2, defaultQuantity: 1, },
    { name: "Lantern", namePlural: "Lanterns", costUnit: 10, defaultQuantity: 1, },
    { name: "Lockpick", namePlural: "Lockpicks", costUnit: 20, defaultQuantity: 1, },
    { name: "Map", namePlural: "Maps", costUnit: 20, defaultQuantity: 1, },
    { name: "Mirror", namePlural: "Mirrors", costUnit: 5, defaultQuantity: 1, },
    { name: "Oil flask", namePlural: "Oil flasks", costUnit: 2, defaultQuantity: 1, },
    { name: "Pole", namePlural: "Poles", costUnit: 1, defaultQuantity: 1, },
    { name: "Ration", namePlural: "Rations", costUnit: 3, defaultQuantity: 1, },
    { name: "Rope", namePlural: "Ropes", costUnit: 1, defaultQuantity: 1, },
    { name: "Sack", namePlural: "Sacks", costUnit: 1, defaultQuantity: 1, },
    { name: "Shovel", namePlural: "Shovels", costUnit: 5, defaultQuantity: 1, },
    { name: "Stake", namePlural: "Stakes", costUnit: 0.2, defaultQuantity: 6, },
    { name: "Spike", namePlural: "Spikes", costUnit: 1, defaultQuantity: 6, },
    { name: "Tinderbox", namePlural: "Tinderboxes", costUnit: 10, defaultQuantity: 1, },
    { name: "Torch", namePlural: "Torches", costUnit: 0.2, defaultQuantity: 6, },
    { name: "Waterskin", namePlural: "Waterskins", costUnit: 3, defaultQuantity: 1, },
];

export let namesPrefixes = [
    "Clubfoot",
    "Crazy",
    "Do-Nothing",
    "One-Eyed",
    "Blind",
    "Brave",
    "Accursed",
    "Bald",
    "Cruel",
    "Gentle",
    "Good",
    "Grim",
    "Holy",
    "Hairy",
    "Lame",
    "Mad",
    "Old",
    "Pale",
    "Quiet",
    "Small",
    "Strong",
    "Swift",
    "Tall",
    "Terrible",
    "Wicked",
    "Wise",
];

export let namesPrimary = [
    "Blaine",
    "Matthew",
    "Morgan",
    "Francisco",
    "James",
    "Richard",
    "Dinadan",
    "Alan",
    "Aldred",
    "Eluard",
    "Arnold",
    "Henry",
    "Basil",
    "Jocelyn",
    "Cyr",
    "Balin",
    "George",
    "Eliot",
    "Frederick",
    "Alexander",
    "Percival",
    "Anselm",
    "Albert",
    "Urian",
    "Tristram",
    "Berenger",
    "Martin",
    "Merek",
    "Herman",
    "Hildebrand",
    "Edwin",
    "Gilbert",
    "Bliant",
    "Bennet",
    "Bryce",
    "Castor",
    "Giles",
    "Gunter",
    "Bernard",
    "Arthur",
    "Nigel",
    "Lucan",
    "Lionel",
    "Bartholomew",
    "Bardolph",
    "Barnabas",
    "Bertram",
    "Wolfstan",
    "Hardwin",
    "Hamond",
    "Faramond",
    "Herbert",
    "Alisander",
    "Ulric",
    "Galleron",
    "Solomon",
    "Sampson",
    "Tobias",
    "Charles",
    "Diggory",
    "Drogo",
    "Hugh",
    "Baudwin",
    "Everard",
    "Nicholas",
    "Leofwin",
    "Amis",
    "Ranulf",
    "Fulke",
    "Theobald",
    "Rowan",
    "Geoffrey",
    "Gervase",
    "Gerard",
    "Godwyn",
    "Philip",
    "Warin",
    "Warner",
    "Thomas",
    "Brom",
    "Hamon",
    "Thurstan",
    "Robert",
    "Roland",
    "Rolf",
    "Walter",
    "Laurence",
    "Reginald",
    "Aglovale",
    "Sayer",
    "Timm",
    "Piers",
    "Cerdic",
    "Randel",
    "Denis",
    "Elias",
    "Gabriel",
    "Hector",
    "Humphrey",
    "Gamel",
    "Gregory",
    "Jasper",
    "Jeremy",
    "Isaac",
    "Ingram",
    "Isembard",
    "Manfred",
    "Ives",
    "William",
    "Lucius",
    "Wymond",
    "Lambert",
    "Blaise",
    "Griffith",
    "Mabon",
    "Hubert",
    "Gerald",
    "Eustace",
    "Emory",
    "Adam",
    "Adelard",
    "Alphonse",
    "Turstin",
    "Guy",
    "Peter",
    "Osric",
    "Ogier",
    "Gareth",
    "Maynard",
    "Miles",
    "Elaine",
    "Sarah",
    "Sela",
    "Sigga",
    "Susanna",
    "Althea",
    "Alma",
    "Artemisia",
    "Anne",
    "Anais",
    "Acelina",
    "Aelina",
    "Aldith",
    "Audry",
    "Augusta",
    "Brangwine",
    "Bridget",
    "Genevieve",
    "Guinevere",
    "Catelin",
    "Caterina",
    "Dionisia",
    "Mary",
    "Molly",
    "Margaret",
    "Margery",
    "Martha",
    "Elizabeth",
    "Elysande",
    "Cristina",
    "Giselle",
    "Regina",
    "Ricolda",
    "Roana",
    "Barbetta",
    "Bertha",
    "Clarice",
    "Amelina",
    "Cecily",
    "Edith",
    "Elle",
    "Juliana",
    "Ivette",
    "Adelina",
    "Agnes",
    "Alis",
    "Alyson",
    "Dameta",
    "Paulina",
    "Petronilla",
    "Edeva",
    "Eglenti",
    "Evelune",
    "Emeline",
    "Emma",
    "Joan",
    "Johanna",
    "Lavina",
    "Lena",
    "Lovota",
    "Lillian",
    "Maud",
    "Milicent",
    "Magdalen",
    "Isabella",
    "Caesaria",
    "Douglas",
    "Delia",
    "Sapphira",
    "Sophronia",
    "Tephania",
    "Theda",
    "Thora",
    "Odelina",
    "Oliva",
    "Orella",
    "Venetia",
    "Ysmeine",
    "Gracia",
    "Gratia",
    "Swanhild",
    "Sybil",
    "Mathilde",
    "Ida",
    "Ingerith",
    "Isemay",
    "Celestria",
    "Constance",
    "Eleanor",
    "Amicia",
    "Avina",
    "Athelina",
    "Eva",
    "Gundred",
    "Felicia",
    "Floria",
    "Isolda",
    "Linota",
    "Cassandra",
    "Lucia",
    "Helewisa",
    "Justina",
    "Joyce",
    "Joya",
    "Nesta",
    "Sabina",
    "Gisela",
    "Rosa",
    "Rosamund",
    "Evaine",
    "Viviane",
    "Laudine",
    "Letia",
    "Leticia",
    "Legarda",
    "Lia",
    "Lunete",
    "Florence",
    "Gwendolen",
    "Nicola",
    "Blanche",
    "Beatrice",
    "Marie",
    "Marion",
    "Mirielda",
];

export let namesSuffixes = [
    "the Hard",
    "the Soft",
    "of the North",
    "of the East",
    "of the South",
    "of the West",
    "the Black",
    "the White",
    "the Red",
    "the Yellow",
    "of the Wood",
    "of the Mountain",
    "of the Valley",
    "of the River",
    "of the Lake",
    "the Elder",
    "the Younger",
    "the Brave",
    "the Great",
    "the Magnificent",
    "the Able",
    "the Accursed",
    "the Bald",
    "the Bear",
    "the Cruel",
    "the Damned",
    "the Exile",
    "the Gentle",
    "the Good",
    "the Grim",
    "the Hammer",
    "the Holy",
    "the Hairy",
    "the Impaler",
    "the Kind",
    "the Lame",
    "the Lion",
    "the Wolf",
    "the Mad",
    "the Old",
    "the Pale",
    "the Quiet",
    "the Rose",
    "the Seer",
    "the Small",
    "the Spider",
    "the Strong",
    "the Swift",
    "the Tall",
    "the Terrible",
    "the Wicked",
    "the Wise",
    "of the Sun",
    "of the Moon",
    "Fairhair",
    "Bloodaxe",
    "Crookback",
    "Flatnose",
    "Forkbeard",
    "Greyfell",
    "Greymantle",
    "Longshanks",
    "Ironside",
    "Moneybags",
    "Oathbreaker",
    "One-Eye",
    "Ploughpenny",
    "Roundhead",
    "Thunderbolt",
    "Oakeshott",
];

export let vocations = [
    // Warriors
    "Barbarian",
    "Bounty Hunter",
    "Crusader",
    "Gladiator",
    "Knight",
    "Outrider",
    "Pit Fighter",
    "Pugilist",
    "Templar",
    "Vigilante",
    "Warrior",

    // Warrior-Mages
    "Battlemage",
    "Paladin",
    "Spellsword",
    "Warpriest",

    // Mages
    "Cleric",
    "Conjurer",
    "Demonologist",
    "Diviner",
    "Druid",
    "Elementalist",
    "Exorcist",
    "Healer",
    "Illusionist",
    "Mage",
    "Medium",
    "Mystic",
    "Necromancer",
    "Oracle",
    "Priest",
    "Psion",
    "Psychic",
    "Shaman",
    "Soothsayer",
    "Sorcerer",
    "Summoner",
    "Thaumaturgist",
    "Warlock",
    "Warmage",
    "Wizard",

    // Mage-Rogues

    // Rogues
    "Acrobat",
    "Agent",
    "Archer",
    "Assassin",
    "Bard",
    "Duelist",
    "Fencer",
    "Hunter",
    "Marksman",
    "Monk",
    "Ninja",
    "Ranger",
    "Rogue",
    "Scout",
    "Spy",
    "Thief",

    // Scholars
    "Alchemist",
    "Apothecary",
    "Astronomer",
    "Doctor",
    "Engineer",
    "Medic",
    "Numerologist",
    "Philosopher",
    "Surgeon",

    // Mundane
    "Aristocrat",
    "Merchant",
    "Orator",
    "Pilgrim",
    "Pirate",
    "Sailor",

    // Other
    "Inquisitor",
];

export let quirks = [
    "Used to be a farmer",
    "Family eaten by trolls",
    "Wants to learn how to use magic",
    "Terribly afraid of undead",
    "Always sharpening or polishing weapons",
    "Constantly looks over their shoulder",
    "Extremely forgetful",
    "Scion to an ancient empire",
    "Always singing sea shanties",
    "Hates the dark",
    "Collects small shiny objects",
    "Composes poems",
    "Composes ballads",
    "Has a map of an ancient lost civilization",
    "Has a scroll in a lost tongue",
    "Teeth stained from chewing tobacco",
];