function getAffiliation() {
    let affiliations = [
        'Wicker Men',
        'Circle of Cernunnos',
        'Church of Crom',
        'Church of Mitra',
        'Temple of Brighid',
        'Cult of Set',
        'Cult of Nergal',
        'Merry Men',
        'Cult of the Black Amphora',
        'Order of the Sphinx',
        'Order of the Rose',
        'Order of the Basilisk',
        'Order of the Candle',
        'Order of the Lantern',
        'Order of the Hearth',
        'Skylords',
        'Blackhands',
        'Thieves\' Guild',
        'Bloody Cabal',
        'Shadow Cult',
        'Guild of Sorcerers',
        'Society of Scrutinous Scholars',
        'Royal Gardeners\' Society',
        'The Sulfur Company',
        'Merchants\' Guild',
        'Royal Arcane Institute',
        'Institute of the Arcane',
        'Aldred\'s Two Hundred',
        'Highpeak Clan',
        'Barrett\'s Privateers',
        'Northwest Passage Explorers',
        'Finch\'s Giants',
        'Bramble Bastards',
        'Witches of the Westmorland',
        'The Night Guard',
        'Scarborough Sorcerers',
        'Herbal Guild',
        'Barrow Delvers\' Society',
        'The Lock Keepers',
        'Marduk\'s Last Watch',
        'Woodbridge Dogs',
        'House of the Holy',
        'Blackdogs',
        'Sword of St. Tristan',
        'House of Red',
        'Harbingers of the Dark Star',
        'Children of the Moon Mountains',
        'Dire Wolves',
        'Shield-Maidens of Veborg',
        'Canso Witch-Hunters',
        'Sun Warriors',
        'Valkyries of Sigyn',
        'The Wild Boars',
        'Nightblades',
        'Masters of the Universe',
        'Wheel of Fire',
        'Royal Metallurgists',
        'The Alloy Supreme',
        'Zenith\'s Hammer',
        'The Transcendants',
    ];

    return affiliations.random();
}